version: '3'

services:
  db:
    image: postgres
    restart: on-failure
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: python3 /src/manage.py runserver 0.0.0.0:8000
    restart: on-failure
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
