# Generated by Django 2.0.2 on 2019-10-20 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesItinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Activity')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Itinerary')),
            ],
        ),
        migrations.RemoveField(
            model_name='dayrange',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='dayrange',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='dayrangeactivities',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='dayrangeactivities',
            name='day_range',
        ),
        migrations.DeleteModel(
            name='DayRange',
        ),
        migrations.DeleteModel(
            name='DayRangeActivities',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='activities',
            field=models.ManyToManyField(through='website.ActivitiesItinerary', to='website.Activity'),
        ),
    ]
