# Generated by Django 2.0.2 on 2019-10-20 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191020_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiesitinerary',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Itinerary'),
        ),
    ]
